#!/bin/bash

cat >> /home/oracle/.bash_profile <<EOF
export ORACLE_BASE=/opt/oracle
export ORACLE_SID=orcl
export ORACLE_UNQNAME=orcl
export ORACLE_HOME=$ORACLE_BASE/product/11.2.0/dbhome_1
export PATH=$ORACLE_HOME/bin:$PATH
EOF

mount -t tmpfs shmfs -o size=4g /dev/shm

export DISPLAY=hostname:0.0

date
echo "Creating listener..."
su - oracle -c "netca -silent -responseFile /tmp/install/database/response/netca.rsp"

date
echo "Creating database..."
su - oracle -c "dbca -silent -createDatabase -responseFile /tmp/install/dbca.rsp"
echo ""

date
echo "Creating password file..."
cd $ORACLE_HOME/dbs
su - oracle -c "$ORACLE_HOME/bin/orapwd FILE=orapw$ORACLE_SID password=change_on_install"
echo ""

date
echo "Running catalog.sql..."
cd $ORACLE_HOME/rdbms/admin
cp catalog.sql catalog-e.sql
echo "exit" >> catalog-e.sql
su - oracle -c "sqlplus / as sysdba @?/rdbms/admin/catalog-e.sql > /tmp/catalog.log"
rm catalog-e.sql
echo ""

date
echo "Running catproc.sql..."
cd $ORACLE_HOME/rdbms/admin
cp catproc.sql catproc-e.sql
echo "exit" >> catproc-e.sql
su - oracle -c "sqlplus / as sysdba @?/rdbms/admin/catproc-e.sql > /tmp/catproc.log"
rm catproc-e.sql
echo ""

date
echo "Running pupbld.sql..."
cd $ORACLE_HOME/sqlplus/admin
cp pupbld.sql pupbld-e.sql
echo "exit" >> pupbld-e.sql
su - oracle -c "sqlplus system/manager @?/sqlplus/admin/pupbld-e.sql > /tmp/pupbld.log"
rm pupbld-e.sql
echo ""

echo "Finalizing install and shutting down the database..."
su - oracle -c "sqlplus / as sysdba @?/config/scripts/conf_finish.sql"
echo ""

date
echo "Done! Commit the container now."

